Fix duplicate naming (Accounts service)
altlinux/admx-basealt pull request #23
Opened 2020-09-04 18:08 UTC by alenka26

Fix duplicate naming (Accounts service was there 3 times)

2020-09-04 18:17 UTC, rbapin requested changes

2020-09-04 18:17 UTC, rbapin commented on en-US/basealtsystemdunits.adml
> +      <string id="sshd_service">Secure access daemon (sshd)</string>
i think it should be "Secure **Shell remote** access daemon (sshd)"

2020-09-04 18:17 UTC, rbapin commented on ru-RU/basealtsystemdunits.adml
> +      <string id="sshd_service">Служба защищённого доступа к ресурсам (sshd)</string>
Служба защищённого **удаленного** доступа к ресурсам (sshd)

2020-09-05 02:30 UTC, mastersin commented on ru-RU/basealtsystemdunits.adml
> +      <string id="sshd_service">Служба защищённого доступа к ресурсам (sshd)</string>
Мне кажется, что часть фразы "к ресурсам" ясности не вносит, а вопрос о том, какие ресурсы имеются в виду возникают:
"Служба защищённого удаленного доступа (sshd)".

2020-09-10 13:04 UTC, merged