Added folders mate, screensaver
altlinux/admx-basealt pull request #30
Opened 2021-07-12 11:21 UTC by AlexSP0

Added folders: mate->screensaver

2021-07-17 19:09 UTC, mastersin requested changes

2021-07-17 19:09 UTC, mastersin commented on en-US/basealt.adml
> +      <string id="ALT_General_Help">general options</string>
Это непонятные категории. Хотелось бы увидеть дерево, чтобы это оценить.

2021-07-19 07:24 UTC, AlexSP0 commented on en-US/basealt.adml
> +      <string id="ALT_General_Help">general options</string>
org.mate.Marco содержит следующие группы настроек:
- команды, выпоняемые при нажатии горячих клавиш
- различные настройки отображения графического интерфейса
- имена для рабочих областей
- соответствие горячих клавиш командам
- назначает горячие клавиши для окон графического интерфейса
Более подробную информацию выслал на электронную почту.

2021-08-11 14:56 UTC, ValeraSin requested changes
Нужно все парные политики объединить с классом "Both".

2021-08-11 14:56 UTC, ValeraSin commented on BaseALTGsettings.admx
> +<!--         org.mate.screensaver         -->
Если политика задаётся для машины и юзера, то класс нужно указывать Both, а не две копии делать. Иначе возникают глюки.

Пример из Firefox:
```
<!-- Alphabetization is based on name, so had to add B -->
    <policy name="B_WebsiteFilter_Block" class="Both" displayName="$(string.WebsiteFilter_Block)" explainText="$(string.WebsiteFilter_Block_Explain)" key="Software\Policies\Mozilla\WebsiteFilter\Block" presentation="$(presentation.WebsiteFilter)">
      <parentCategory ref="firefox"/>
      <supportedOn ref="SUPPORTED_FF60"/>
      <elements>
        <list id="WebsiteFilter" key="Software\Policies\Mozilla\Firefox\WebsiteFilter\Block" valuePrefix=""/>
      </elements>
    </policy>
```

2021-10-04 08:20 UTC, closed without merging