Added folder with mate graphic settings
altlinux/admx-basealt pull request #34
Opened 2021-08-02 15:45 UTC by AlexSP0

Added a folder with Mate graphic settings and with settings for the desktop background, window manager, desktop interface, and screensaver.

2021-08-03 18:39 UTC, mastersin requested changes

2021-08-03 18:39 UTC, mastersin commented on en-US/basealtgsettings.adml
> +      <string id= "picture-options_Spanned">spanned</string>
Откуда здесь пробелы перед id ?

2021-08-03 18:39 UTC, mastersin commented on ru-RU/basealtgsettings.adml
> +      <string id= "picture-options_Spanned">spanned</string>
Аналогично

2021-08-03 18:39 UTC, mastersin commented on en-US/basealt.adml
> +      <string id="ALT_Windows_Manager">Windows Manager</string>
Завтра будет "Windows Manager" для KDE, как будет называться ID для категории тоже "ALT_Windows_Manager". Думаю, нужно заранее это планировать под ещё Common и KDE, как минимум.

2021-08-04 07:52 UTC, AlexSP0 commented on en-US/basealtgsettings.adml
> +      <string id= "picture-options_Spanned">spanned</string>
fixed.

2021-08-04 07:52 UTC, AlexSP0 commented on ru-RU/basealtgsettings.adml
> +      <string id= "picture-options_Spanned">spanned</string>
fixed.

2021-08-09 05:20 UTC, AlexSP0 commented on en-US/basealt.adml
> +      <string id="ALT_Windows_Manager">Windows Manager</string>
Исправил.

2021-08-09 05:25 UTC, mastersin commented
А почему ALT_Mate_Screensaver, если везде Mate - суффикс?

2021-08-09 07:53 UTC, AlexSP0 commented
> А почему ALT_Mate_Screensaver, если везде Mate - суффикс?

Поправил, теперь ALT_Screensaver_Mate

2021-08-12 09:23 UTC, mastersin requested changes
Пустые строки в конец текстовых файлов ставить надо.

2021-08-12 09:23 UTC, mastersin commented on BaseALTGsettings.admx
> +</policyDefinitions>
Пустая строка в конце.

2021-08-12 09:23 UTC, mastersin commented on en-US/basealtgsettings.adml
> +</policyDefinitionResources>
Аналогично.

2021-08-12 09:52 UTC, AlexSP0 commented on BaseALT.admx
> +    </category>
Уже починено, данный кусок помечен как outdated.

2021-08-12 09:55 UTC, AlexSP0 commented on en-US/basealt.adml
> +      <string id="ALT_Background_Help">Desktop background settings</string>
Уже починено, данный кусок помечен как outdated.

2021-10-04 08:23 UTC, closed without merging