Added synchonous machine and user setting
altlinux/admx-basealt pull request #37
Opened 2021-10-04 11:25 UTC by AlexSP0

partially edited package settings

2022-02-08 19:02 UTC, mastersin requested changes

2022-02-08 19:02 UTC, mastersin commented on en-US/basealtpackages.adml
> +      <string id="sync_packages_work_user_help">Enable this setting for synchronous work with packages</string>
Аналогично "Synchronous work with packages" - "Enable this setting for synchronous work with packages".

2022-02-10 12:39 UTC, AlexSP0 commented on BaseALTPackages.admx
> +      <supportedOn ref="system:SUPPORTED_AltP8"/>
fixed

2022-02-10 12:39 UTC, AlexSP0 commented on BaseALTPackages.admx
> +    <policy class="Machine" displayName="$(string.packages_install)" explainText="$(string.packages_install_help)" key="Software\BaseALT\Policies\Packages" name="InstallPackagesMachine" presentation=
fixed

2022-02-17 02:57 UTC, mastersin approved these changes
LGFM

2022-02-17 02:57 UTC, merged