Add policies for local users
altlinux/admx-basealt pull request #43
Opened 2021-10-26 11:10 UTC by AlexSP0

Добавлены политики для управления применением групповых политик к локальным пользователям

2022-02-08 19:26 UTC, mastersin requested changes

2022-02-08 19:26 UTC, mastersin commented on BaseALTGroupPolicies.admx
> +      <supportedOn ref="system:SUPPORTED_AltP9"/>
p9?

2022-02-08 19:26 UTC, mastersin commented on en-US/basealtgrouppolicies.adml
> +      <string id="gp_local_users_group_users_help">Disable the application of group policies for users in the users group.</string>
not!

2022-02-08 19:26 UTC, mastersin commented on ru-RU/basealtgrouppolicies.adml
> +      <string id="gp_local_users_group_users_help">Отключение применения групповых политик для пользователей, входящих в группу users.</string>
не входящий

2022-02-08 19:26 UTC, mastersin commented on en-US/basealtgrouppolicies.adml
> +      <string id="gp_local_users_group_users">Group users</string>
Disable for users not 'users' group ? Или чуть по-проще.

2022-02-08 19:26 UTC, mastersin commented on en-US/basealtgrouppolicies.adml
> +      <string id="ALT_GPLocalUsers_Help">Applying Group policies for local users</string>
тавтология

2022-02-08 19:26 UTC, mastersin commented on en-US/basealtgrouppolicies.adml
> +      <string id="gp_local_users_group_users">Group users</string>
Filter local users by 'users' local group.

2022-02-08 19:26 UTC, mastersin commented on en-US/basealtgrouppolicies.adml
> +      <string id="gp_local_users_group_users">Group users</string>
Filter by group

2022-02-08 19:26 UTC, mastersin commented on en-US/basealtgrouppolicies.adml
> +      <string id="gp_local_users_group_localusers">Local users</string>
Enable local users

2022-02-08 19:26 UTC, mastersin commented on en-US/basealtgrouppolicies.adml
> +      <string id="gp_local_users_group_localusers_help">Disable the application of group policies for local users.</string>
Enable group policies applying for local users.

2022-02-08 19:26 UTC, mastersin commented on en-US/basealtgrouppolicies.adml
> +      <string id="gp_local_users_system-uids_help">Disable the application of group policies for users with uid less 500.</string>
Filter local users by uid

2022-02-08 19:26 UTC, mastersin commented on en-US/basealtgrouppolicies.adml
> +      <string id="gp_local_users_system-uids">System uids</string>
Filter by uid

2022-02-17 02:54 UTC, mastersin requested changes
Нужно переделать контролы с числовых на строковые.

2022-02-17 02:54 UTC, mastersin commented on BaseALTGroupPolicies.admx
> +      </disabledValue>
Все новые контролы должны управляться строковые значениями. Старые тоже нужно переделать.

2022-02-18 09:34 UTC, AlexSP0 commented on BaseALTGroupPolicies.admx
> +      </disabledValue>
fixed

2022-03-02 03:31 UTC, mastersin approved these changes
LGTM

2022-03-02 03:32 UTC, merged