Add platform 10
altlinux/admx-basealt pull request #48
Opened 2022-02-09 13:42 UTC by AlexSP0

Add platform 10

2022-02-14 11:39 UTC, mastersin requested changes

2022-02-14 11:39 UTC, mastersin commented on BaseALTProducts.admx
>            <minorVersion name="ALTServerV9_91" displayName="$(string.ALTServerV9_91)" versionIndex="1"/>
Нужно добавить ещё V9_92

2022-02-14 13:01 UTC, AlexSP0 commented on BaseALTProducts.admx
>            <minorVersion name="ALTServerV9_91" displayName="$(string.ALTServerV9_91)" versionIndex="1"/>
добавил.

2022-02-16 20:08 UTC, mastersin approved these changes
LGFM

2022-02-16 20:09 UTC, merged