fix: correction of option name open ldap tls connections in russian
altlinux/admx-basealt pull request #72
Opened 2022-12-16 12:01 UTC by AlexSP0

correction of option names in ldap-tls-cert-check control

2022-12-17 15:28 UTC, mastersin requested changes

2022-12-17 15:28 UTC, mastersin commented on ru-RU/basealtcontrol.adml
> +      <string id="ldap-tls-cert-check_demand">Требование</string>
А почему везде глаголы, а тут существительное - не логично.
Может быть тогда нужно указать "Требовать"?

2022-12-17 19:17 UTC, AlexSP0 commented on ru-RU/basealtcontrol.adml
> +      <string id="ldap-tls-cert-check_demand">Требование</string>
поправил.

2022-12-17 21:54 UTC, mastersin requested changes
А выше? В описании?

2022-12-18 06:26 UTC, AlexSP0 commented
> А выше? В описании?

Поправил

2022-12-29 03:19 UTC, merged